### ISSUE TITLE
Data types and values that affect full dump

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dtle#1006]

**Comment by LordofAvernus** [comment]
## 全量同步导致同步停止的数据类型

-  BINARY_DOUBLE 特殊类型值问题
         inf -inf nan
         增量过程将几个数值转换为NULL
- DATE 时间格式问题
replace into `TEST`.`DATE_COLUMNS`  values ('0',NULL),('1','0001-01-01T00:00:00Z'),('2','9999-12-31T00:00:00Z'),('3','2022-02-21T21:02:44Z')

- DECIMAL
     数值长度问题 ('1','1e+28'),('2','-1e+28') 长度问题
      replace into `TEST`.`DECIMAL_COLUMNS`  values ('0',NULL),('1','1e+28'),('2','-1e+28'),('3','0'),('4','100')

- LONG 源端抽取不支持

-  INTERVAL_DAY 时间格式问题
       replace into `TEST`.`INTERVAL_DAY_COLUMNS`  values ('0',NULL),('1'
,'+999999999 23:59:59.999999'),('2','+3294967297 233:197:197.3294967'),('3','+11 10:09:00.000000'),('4','+100 10:00:00.000000'),('5','+00 09:30:00.000000'),('6','+00 00:15:30.000000')

- NUMBER out of range 长度问题
replace into `TEST`.`NUMBER_38_COLUMNS`  values ('0',NULL),('1','1e+38'),('2','-1e+38'),('3','0'),('4','1')

- TIMESTAMP 类型
    Error 1292: Incorrect datetime value: '0001-01-01T00:00:00Z' 时间格式
     replace into `TEST`.`TIMESTAMP_COLUMNS`  values ('0',NULL),('1','0001-01-01T00:00:00Z')
,('2','9999-12-31T23:59:59.999999999Z'),('3','2022-07-04T18:30:25.650293Z'),('4','2022-07-04T18:30:25.659959Z'),('5','2022-07-04T10:30:25.670223Z'),('6','2022-02-21T10:1

- 数值类型的  9999999.99999 都失败了

**Comment by LordofAvernus** [comment]
1.数值类型异常问题
         尝试更新驱动 
	 "github.com/sijms/go-ora/v2" 替换为	 "github.com/godror/godror"
	 godror连接Oracle 需要安装Oracle Full Client或Instant Client 驱动程序

**Comment by asiroliu** [comment]
字符类型null值错误
```
CREATE TABLE ACTION_DB.CHAR_255_COLUMNS(col1 INT, col2 CHAR(255))
CREATE TABLE ACTION_DB.CHAR_2000_COLUMNS(col1 INT, col2 CHAR(2000))
CREATE TABLE ACTION_DB.CHARACTER_255_COLUMNS(col1 INT, col2 CHARACTER(255))
CREATE TABLE ACTION_DB.CHARACTER_2000_COLUMNS(col1 INT, col2 CHARACTER(2000))
CREATE TABLE ACTION_DB.NCHAR_255_COLUMNS(col1 INT, col2 NCHAR(255))
CREATE TABLE ACTION_DB.NCHAR_1000_COLUMNS(col1 INT, col2 NCHAR(1000))
CREATE TABLE ACTION_DB.NCHAR_VARYING_COLUMNS(col1 INT, col2 NCHAR VARYING(2000))
```
oracle
INSERT INTO ACTION_DB.CHAR_255_COLUMNS VALUES (0, NULL)；
MySQL全量
'COL2':  ‘’
MySQL增量
'COL2': null

**Comment by asiroliu** [comment]
目标端数据类型错误
oracle建表
```
CREATE TABLE ACTION_DB.INTEGER_COLUMNS(col1 INT, col2 INTEGER)
CREATE TABLE ACTION_DB.INT_COLUMNS(col1 INT, col2 INT)
```

MySQL 验证：
```
SELECT DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION FROM COLUMNS WHERE TABLE_SCHEMA='ACTION_DB' AND TABLE_NAME='<oracle_type>' AND COLUMN_NAME='COL2';
```
预期：
('DATA_TYPE', 'int'), ('CHARACTER_MAXIMUM_LENGTH', None), ('NUMERIC_PRECISION', 10), ('NUMERIC_SCALE', 0), ('DATETIME_PRECISION', None)
实际：
{'DATA_TYPE': 'double', 'CHARACTER_MAXIMUM_LENGTH': None, 'NUMERIC_PRECISION': 22, 'NUMERIC_SCALE': None, 'DATETIME_PRECISION': None}

----

```
CREATE TABLE ACTION_DB.SMALLINT_COLUMNS(col1 INT, col2 SMALLINT)
```
预期：
('DATA_TYPE', 'decimal'), ('CHARACTER_MAXIMUM_LENGTH', None), ('NUMERIC_PRECISION', 38), ('NUMERIC_SCALE', 0), ('DATETIME_PRECISION', None)
实际：
{'DATA_TYPE': 'double', 'CHARACTER_MAXIMUM_LENGTH': None, 'NUMERIC_PRECISION': 22, 'NUMERIC_SCALE': None, 'DATETIME_PRECISION': None}

**Comment by asiroliu** [comment]
数据错误
```
CREATE TABLE ACTION_DB.INTERVAL_YEAR_COLUMNS(col1 INT, col2 INTERVAL YEAR(9) TO MONTH)
CREATE TABLE ACTION_DB.INTERVAL_DAY_COLUMNS(col1 INT, col2 INTERVAL DAY(9) TO SECOND(9))
```
```
INSERT INTO ACTION_DB.INTERVAL_YEAR_COLUMNS VALUES (1, INTERVAL '999999999-11' YEAR(9) TO MONTH)
```
MySQL全量
'COL2': '+999999999-11'
MySQL增量
'COL2': '999999999-11'

```
INSERT INTO ACTION_DB.INTERVAL_DAY_COLUMNS VALUES (1, INTERVAL '999999999 23:59:59.999999999' DAY(9) TO SECOND(9))
```
MySQL全量
'COL2': '+999999999 23:59:59.999999999'
MySQL增量
'COL2': '-4549241255539769345'

**Comment by LordofAvernus** [comment]
1. INTERVA_xxx类型未能完全支持（受限于godror driver）
2. INT/INTEGER/SMALLINT 由于oracle内部存储结构为number，当前的获取建表语句得到的结果  无法与真正执行的建表语句一致.故同步的表结构与增量有差异（增量从日志读取的建表语句，基本与真实建表语句一致）.
3.  字符类型的的NULL值与空值，使用godror读取的出来的结果一致（已提issue，待godror修复）
https://actiontech.github.io/dtle-docs-cn/5/5.4_columns_mapping.html
