### ISSUE TITLE
dtle当前是否支持 web admin UI 管理任务

### ISSUE THREAD

**Issue by callmedba** [actiontech/dtle#1039]
浏览阅读dble安装部署文档时，有看到可以通过 curl -XPOST 和 curl -XGET 的方式创建和查看任务，但没看到web admin管理界面的相关介绍，在路线图里也没找到说明。

请问当前支持web ui 管理任务吗 ，类似 canal admin 的功能

谢谢

**Comment by re-f** [comment]
Web UI目前在企业版提供
