### ISSUE TITLE
create job with existing id

### ISSUE THREAD

**Issue by ikarishinjieva** [actiontech/dtle#242]
**Description**

**Steps to reproduce the issue:**
1. When existing job is running, the creation API return `Success: true`, but it actually fail
2. When existing job is pause or dead, the new job replace existing one

**Describe the results you received:**
1. dtle should check id uniqueness

**Describe the results you expected:**

**Output of `./dtle version`:**

```
(not available)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
On dtle 3.x, when running a job with an existing name (ID), nomad will
- stop and re-start the task if the job config has been updated
- re-start the task if the task has failed
- do nothing if there is no update and task is running
