### ISSUE TITLE
Spread: The use restrictions of DDL , different records for the same table of a single MySQL are distributed to multiple MySQL (binglog-sql)

### ISSUE THREAD

**Issue by zhangjingwen198817** [actiontech/dtle#300]
**Problem Description:**
when create a database table level replication, the Dtle will not support  the below mysql statement.
```        
alter table  old_tablename  rename new_tablename
insert child values(1,'z','ww',1);
```
Version:(git: master bbabd4f89d2b1f72f51fdac1d516a954119bbb2c)
**Prepare  Test Environment:**
Prepare 3 mysql instances on different hosts.(for example:10.196.30.94 ,10.186.30.90, 10.186.30.7 )

**Steps To Reproduce:**
Step1:   execute the below mysql statements on source database (10.186.30.94):
```
create database testHA;
use testHA;
CREATE TABLE `testPK_1` (
  `id` int(11)  NOT NULL,
  first_name text not null,
  last_name text,
  views int(10),
  primary KEY `id` (`id`)
);
```
Step2: Create two tasks on Dtle to complete the following scenario，different records for the same table of a single MySQL are distributed to multiple MySQL.

Step3:  start two tasks with the attachment scripts.
[job1.json.txt](https://github.com/actiontech/dtle/files/2356202/job1.json.txt)
[job2.json.txt](https://github.com/actiontech/dtle/files/2356203/job2.json.txt)
For example:
```
curl -H "Accept:application/json" -XPOST "10.186.30.94:8190/v1/jobs" -d @job1.json
curl -H "Accept:application/json" -XPOST "10.186.30.94:8190/v1/jobs" -d @job2.json
```

Step4: execute the below mysql statement on source database(10.186.30.94).
```
alter table testPK_1 rename  child;
```
Step5: insert data on source database;
```
insert child values(1,'z','ww',1);
```

**Actual Resluts:**
1. The Dtle sync the table name on target database.
2. The Dtle have an error log:
```
2018/09/06 13:50:45.151050 [DEBUG] [3e603e2c-01c6-c9b0-d541-6c23ac17c7b1] mysql.reader: query event: schema: testha, quer
y: alter table testPK_1 rename child
2018/09/06 13:50:45.151050 [DEBUG] [6b18f5c1-a1c4-6629-e35f-f3b3c9fe7d8f] mysql.reader: query event: schema: testha, quer
y: alter table testPK_1 rename child
2018/09/06 13:50:45.151292 [DEBUG] [3e603e2c-01c6-c9b0-d541-6c23ac17c7b1] mysql.reader: ddl is create table
2018/09/06 13:50:45.151290 [DEBUG] [6b18f5c1-a1c4-6629-e35f-f3b3c9fe7d8f] mysql.reader: ddl is create table
2018/09/06 13:50:45.151985 [WARN] [3e603e2c-01c6-c9b0-d541-6c23ac17c7b1] error handle create table in binlog: GetTableCol
umns: Error 1146: Table 'testha.testpk_1' doesn't exist
2018/09/06 13:50:45.151988 [WARN] [6b18f5c1-a1c4-6629-e35f-f3b3c9fe7d8f] error handle create table in binlog: GetTableCol
umns: Error 1146: Table 'testha.testpk_1' doesn't exist
```
3.Target database can't sync the insert data from source database

**Comment by yaqigithub** [comment]
complete （Dtle 9.9.9.9 (git: master 203100a4b7f72fe636c3461c97a4fe13ac7c7cdf)）
