### ISSUE TITLE
双向复制和建表语句

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#337]
**Description**

Fail to support the 'scenario of reciprocating migration on the same table'

**Steps to reproduce the issue:**
1. Both MySQL108 and MySQL144 have empty table db1.tb1  `create table db1.tb1(a int)`
2. Create job1(MySQL108→MySQL144) for `db1.tb1`  & job2(MySQL144→MySQL108) for `db1.tb1`
3. The state of job1 automatically changes into **stop** after a while.

**Describe the results you received:**

1. Dtle.log flush qulikly once job1 and job2 established.
2. Gtid flush rapidly both in MySQL108 and in MySQL144.
3. The state of job1 automatically changes into **stop** after a while.
![image](https://user-images.githubusercontent.com/17309012/47206993-aa57e700-d3bc-11e8-9919-bac446856906.png)

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master e91675f315802071b19c677d0c22c88fdbeff687)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**
1. DTLE config
```
# Setup data dir
data_dir = "/opt/udup/data"
log_file = "/opt/udup/var/log/udup/udup.log"
log_level = "DEBUG"
bind_addr = "10.186.30.4"

ui = true
ui_dir = "/opt/udup-frontend-master"

# Modify our port to avoid a collision with server
ports {
    http = 8190
}

# Enable the manager
manager {
    enabled = true

    # Self-elect, should be 3 or 5 for production,
    # Addresses to attempt to join when the server starts.
    join = [ "10.186.30.4" ]
}

# Enable the agent
agent {
    enabled = true
    managers = ["10.186.30.4:8191"]
}

addresses {
  http = "10.186.30.4"
  rpc = "10.186.30.4"
  serf = "10.186.30.4"
}
advertise {
  http = "10.186.30.4"
  rpc = "10.186.30.4"
  serf = "10.186.30.4"
}
```
2. job.json
 - [job1.txt](https://github.com/actiontech/dtle/files/2494978/job1.txt)

 - [job2.txt](https://github.com/actiontech/dtle/files/2494980/job2.txt)
 
3. dtle.log :  [dtle_log.txt](https://github.com/actiontech/dtle/files/2494991/dtle_log.txt)

**Comment by ffffwh** [comment]
Workaround
- set `"SkipCreateDbTable": true`

**Comment by Dinosauria** [comment]
> Workaround
> 
> * set `"SkipCreateDbTable": true`

It seems to be an effective way to use it. 
All the results mentioned above didn't show up any more in Dtle 9.9.9.9 (git: master 8cfef1b6ddd14778343d2fa8bad081cfc1befc31)

**Comment by ffffwh** [comment]
A workaround is a temporary solution.
A formal fix is still required.
