### ISSUE TITLE
字段长度超过限制

### ISSUE THREAD

**Issue by skymoou** [actiontech/dtle#342]
CREATE TABLE IF NOT EXISTS actiontech_udup.gtid_executed_v2 (
    job_uuid binary(16) NOT NULL COMMENT 'unique identifier of job',
    source_uuid binary(16) NOT NULL COMMENT 'uuid of the source where the transaction was originally executed.',
    interval_gtid text NOT NULL COMMENT 'number of interval.'
);

当做全量同步的时候， interval_gtid 字段长度不够，直接导致job失败 报错信息：
2018/10/25 10:31:09.274531 [ERR] agent: Task "Dest" for alloc "589aa77c-db36-b485-b36d-42b8f3ff2a3d" failed: Wait returned exit code 2, and error Error 1406: Data too long for column 'interval_gtid' at row 1

**Comment by skymoou** [comment]
建议可以将字段长度适当修正，增加字段长度

**Comment by ffffwh** [comment]
Two considerations
- `text` can hold 64KB.
  - while `mediumtext`: 16MB, `longtext`: 4GB
- Discrete gtid gno values make us cannot store it in intervals like `a-b:c-d`
  - Use a better scheme to store the values

**Comment by ffffwh** [comment]
75a3d86

fix _ #342: Data too long for column 'interval_gtid'  …
- use longtext (4GB) instead of text (64KB)
- migrate gtid_executed_v2 to gtid_executed_v3
- prevent task if future gtid_executed table present

TODO gtid_executed_v4
- compression
- binary storage

**Comment by ffffwh** [comment]
NB: migrating gtid_executed_v2 to gtid_executed_v3 is **one-way**.
