### ISSUE TITLE
There is no heartbeat mechanism to detect if you can connect to dest mysql

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#352]
**Description**
There is no heartbeat mechanism to detect if you can connect to dest mysql,until a sql happened on src mysql will the error be found.

**Steps to reproduce the issue:**
1. Post a job
2. Stop the dest mysql
3. Observe the job status
4. `INSERT` sql on src

**Describe the results you received:**
After stop the dest mysql,the status of job keep 'running' .
until a sql happened on src mysql will the error be found.

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master ea8483db80155ce736935029ff27c8362e677b02)
```

**Additional details (log, config, job config etc):**
logs_here: [dtle_log.txt](https://github.com/actiontech/dtle/files/2564485/dtle_log.txt)

**Comment by ffffwh** [comment]
fb21089b changed some behavior. Should re-test.

**Comment by Dinosauria** [comment]
Verified in Dtle 9.9.9.9 (git: master 3db3e66676698648183df520a653ba9a3a39d96c)
