### ISSUE TITLE
 Parameter is invalid（job：ApproveHeterogeneous）

### ISSUE THREAD

**Issue by leixia2018** [actiontech/dtle#354]
**Description**

**Steps to reproduce the issue:**
1.No matter how to set the value，ApproveHeterogeneous of value is  true

**Describe the results you received:**

**Describe the results you expected:**

**Output of `./dtle version`:**

```
git: master ea8483db80155ce736935029ff27c8362e677b02
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
`ApproveHeterogeneous` is obsolete and always be `true`.
