### ISSUE TITLE
Incorrect command execution results prompted incorrectly

### ISSUE THREAD

**Issue by leixia2018** [actiontech/dtle#371]
**Description**

**Steps to reproduce the issue:**
1.
```
[root@node4 opt]# /usr/bin/dtle job-status 
No running jobs
[root@node4 opt]# /usr/bin/dtle job-status -address=http://172.100.9.4:8190
ID                                    Type         Status
e4c9eddf-698d-fd68-b246-ddc61734bd12  synchronous  dead
```
**Describe the results you received:**

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 2.18.11.0 (git: 2.18.11.0 53cf2c15974a143e89c1b6783d75cd9a0ff215d6)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
dtle 2.x is deprecated.
