### ISSUE TITLE
Close a session with a temporary table created may cause job 'dead'

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#384]
**Description**

Close a session with a temporary table created may cause job 'dead'

**Steps to reproduce the issue:**
1. open a session on src and create a temporary table in src mysql ,e.g. `create temporary table sbtest1 as select * from sbtest1 where id>500;`
2. job runs normally 
3. when close the session
4. job dead immediately

**Describe the results you received:**

Close a session with a temporary table created may cause job 'dead'

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master d817e0269e3cf393bac011ff4d498d07118d0542)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

1. default config path: /etc/dtle/dtle.conf
[job_conf.txt](https://github.com/actiontech/dtle/files/2712416/job_conf.txt)

2. job config
[job_json.txt](https://github.com/actiontech/dtle/files/2712415/job_json.txt)

3. dtle.log
[dtle_log.txt](https://github.com/actiontech/dtle/files/2712414/dtle_log.txt)

**Comment by ffffwh** [comment]
tidb parser 不支持 `create temporary table a.a (id int primary key)`

关联问题: 执行DDL应当忽略dst mysqld的某些错误.

**Comment by Dinosauria** [comment]
Dtle 9.9.9.9 (git: master 3db3e66676698648183df520a653ba9a3a39d96c)
