### ISSUE TITLE
Fail to applier Chinese character from binlog to sql when using charset of latins 

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#388]
**Description**

Fail to applier Chinese character from binlog to sql when using charset of latins 

**Steps to reproduce the issue:**
1. create a job with DB level
2. create a table which has char columns and with  DEFAULT CHARSET=latin2
 ```sql
create table char_columns(id int(11) not null primary key,c_char char(255)) ENGINE=InnoDB DEFAULT CHARSET=latin2;
 ```
3. connect src mysql,  `charset latin2;` then insert a some recodes one of which using Chinese character, 
```sql
insert into char_columns values (0,NULL);
insert into char_columns values (1,'');
insert into char_columns values (2,' ');
insert into char_columns values (3,'a a a ');
insert into char_columns values (4,'abcdefghijklmnopqrstuvwxyz');
insert into char_columns values (5,'ABCDEFGHIJKLMNOPQRSTUVWXYZ');
insert into char_columns values (6,'~`!@#$%^&*()-=_+{}[]|:;<>,.?/');
insert into char_columns values (7,'1234567890');
insert into char_columns values (8,1234567890);
insert into char_columns values (9,'数据库sql测试');
```

**Describe the results you received:**

1. All lines of recodes copy to dest except the last line
2. Job status turned 'dead'

**Describe the results you expected:**

All lines copy to dest

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master d817e02)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

In mysql native copy , all lines copy to slave mysql:
![image](https://user-images.githubusercontent.com/17309012/50679603-16063380-103f-11e9-812f-774aa0fead4c.png)

**Additional details (log, config, job config etc):**

dtle.log
```
2019/01/04 15:50:39.258132 [DEBUG] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] mysql.applier: ApplyBinlogEvent: a dml event
2019/01/04 15:50:39.258149 [DEBUG] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] ApplyBinlogEvent. args: [9 数据库sql测试]
2019/01/04 15:50:39.258272 [ERR] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] mysql.applier: gtid: 8868d98f-af5e-11e8-9aa9-0242ac110002:937, error: Error 1366: Incorrect string value: '\xE6\x95\xB0\xE6\x8D\xAE...' for column 'c_char' at row 1
2019/01/04 15:50:39.258391 [ERR] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] mysql.extractor. error: applier
2019/01/04 15:50:39.258455 [DEBUG] setState 4
2019/01/04 15:50:39.258465 [DEBUG] setState.SaveState
2019/01/04 15:50:39.258523 [INFO] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] mysql.applier: Shutting down
2019/01/04 15:50:39.258536 [DEBUG] [22dd2d5c-a508-aa13-73ca-27d8aa3fdbe9] mysql.applier: worker: 0. after ApplyBinlogEvent. GNO: 937
```

**Comment by Dinosauria** [comment]
Both latin1 and latin2 do not support  Chinese character in data type of :
* char
* varchar
* tinytext
* text
* mediumtext
* longtext

**Comment by ffffwh** [comment]
- latin1/2字符集不包含中文
- MySQL在插入latin表时, 有特殊逻辑

> MySQL下，latin表会对自己表述范围外的字符不会做任何处理，所以latin表中
> 存储其他编码的数据是可以实现的。

前提是connection charset要设置成latin.

由于多个表字符集可能不同, dtle applier一律使用utf8mb4作为connection charset, 故不能在latin表中插入中文. 

总之, 在latin表中使用中文是不规范的做法.
