### ISSUE TITLE
Wrong charset on dest when applier chinese character in gbk

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#391]
**Description**

1. On src，create a table with default charset **gbk**
2. On src，`set names gbk;` and `insert` a records in chinese character
3. On dest，check the records，with `set names utf8` ，we got the right chinese character，but when `set names gbk`,  we got wrong chinese character，and this phenomenon is unreasonable

**Steps to reproduce the issue:**
1. create a table with default charset **gbk**
```sql
create table char_columns(id int(11) not null primary key,c_char char(255)) ENGINE=InnoDB DEFAULT CHARSET=gbk;
```
2. create a job of the table `char_columns` ，and we get the same table definetions on dest as which on src.
![image](https://user-images.githubusercontent.com/17309012/50886594-cf904a80-142b-11e9-80f7-bc3e163ffc39.png)

3. On src，exec `set names gbk;` and `insert into char_columns values (9,'数据库sql测试');`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/17309012/50886513-8a6c1880-142b-11e9-96d7-efe92fa1a249.png)

**Describe the results you expected:**

In native mysql replication:

![image](https://user-images.githubusercontent.com/17309012/50887053-1c285580-142d-11e9-977e-104fb18084bf.png)

![image](https://user-images.githubusercontent.com/17309012/50887217-8ccf7200-142d-11e9-97c9-b8108f2cebc7.png)

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master c0d5ca0e88218eeb83af03ba57c4c4a3ce123336)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

1. Always happened in incremental copy(Never happened in full copy)
2. May affected data type:
* char
* varchar
* tinytext
* text
* mediumtext
* longtext

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
1. re-test on recent version
2. make sure the data is inserted with the right encoding
   - terminal data could always be utf-8
   - https://zhuanlan.zhihu.com/p/488965227
