### ISSUE TITLE
双数据中心只同步DDL的需求

### ISSUE THREAD

**Issue by yiwenshuo** [actiontech/dtle#392]
需求1：两个数据源A，B，需要在A库的DDL同步到B库，B库的DDL同步到A库，目前dtle已经解决了写循环的问题，能否新增只同步DDL 类型的binlog。

需求2：细粒度区分DDL类型，create-table、alter table add 、 alter table drop ，alter table modify ....。 提供matcher 进行过滤同步指定哪一类的DDL type。

**Comment by ffffwh** [comment]
https://dev.mysql.com/doc/refman/5.7/en/alter-table.html

`alter table` can have multiple `alter_specification`:

```sql
alter table a.a1 add val1 int, add val2 int;
```
