### ISSUE TITLE
wrong discription in git-book document，privileges ‘reference’ should be 'references'

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#396]
**Description**

Wrong discription in git-book document，privileges ‘reference’ should be 'references'

https://actiontech.github.io/dtle-docs-cn/4/4.5_mysql_user_privileges.html

![image](https://user-images.githubusercontent.com/17309012/51247156-3a5efa00-19c7-11e9-896d-e09a3339d9a5.png)

**Comment by ffffwh** [comment]
done
