### ISSUE TITLE
When using rpm to upgrade dtle, target data lost

### ISSUE THREAD

**Issue by zhangjingwen198817** [actiontech/dtle#399]
**Version:**
dtle(2.18.11.0) update to Dtle (2.19.01.0) (git: master 7800c6fba69417f742b18c34c049dd673e62108e)

**Repro steps:**

1.Install dtle(2.18.11.0)
2.Create a database level replication task
3.Using sysbench, 500,000 pieces of data were inserted into the database
4.stop job
5.upgrade dtle to 2.19.01.0(rpm  -Uvh --force dtle-9.9.9.9-qa.x86_64.rpm)
6.restart job and wait replication finished
7.check  data consistency
[repro_cmd.txt](https://github.com/actiontech/dtle/files/2864391/repro_cmd.txt)

**Result:**
1.Target data lost

![qq 20190214175637](https://user-images.githubusercontent.com/38240468/52778863-e6a50680-3081-11e9-8587-f6313974cc62.png)

2.below is dtle's log

[result.log](https://github.com/actiontech/dtle/files/2864413/result.log)

**Comment by ffffwh** [comment]
Consistency has been improved in 3.x.
