### ISSUE TITLE
When dest dtle-node was killed while records keep growing，Failover worked with some records missing

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#400]
**Description**

When dest dtle-node was killed while records keep growing，Failover worked with some records missing.

dtle cluster info:

| dtle-node |  role | cluster role | job role |
| ------------- | ------------- | ------------- |------------- |
| dtle-4 | manager & agent | member | src dtle-node  |
| dtle-5 | manager & agent | member | dest dtle-node  |
| dtle-6 | manager & agent | leader | -- |

job info (`"Failover":true`):
``` JSON
{
    "Name":"test",
    "Failover":true,
    "Orders":[],
    "Type":"synchronous",
    "Tasks":[
        {
            "Type":"Src",
            "NodeId":"c198b038-ecd6-255b-dde1-eef7db4244a2",
            "Config":{
                "Gtid":"",
                "SkipCreateDbTable":false,
                "ExpandSyntaxSupport":false,
                "DropTableIfExists":false,
                "ReplChanBufferSize":"600",
                "ChunkSize":"2000",
                "ApproveHeterogeneous":true,
                "ReplicateDoDb":[
                    {
                        "TableSchema":"action_db",
                        "Tables":[]
                    }
                ],
                "ConnectionConfig":{
                    "Host":"172.100.9.1",
                    "Port":"3306",
                    "User":"test1",
                    "Password":"test1"
                }
            }
        },
        {
            "Type":"Dest",
            "NodeId":"2012e7c5-ec1b-09d8-185d-d9f6f63bf283",
            "Config":{
                "SkipCreateDbTable":false,
                "DropTableIfExists":false,
                "ExpandSyntaxSupport":false,
                "ReplChanBufferSize":600,
                "ApproveHeterogeneous":true,
                "ConnectionConfig":{
                    "Host":"172.100.9.2",
                    "Port":"3306",
                    "User":"test2",
                    "Password":"test2"
                }
            }
        }
    ]
}
```

**Steps to reproduce the issue:**
1. prepare table `action_db.sbtest1` with 100000 records by sysbench on src 
2. post a schema level job 'test'，job info as above
3. when job finished，run sysbench `insert.lua` insert another 100000 recodes on table `action_db.sbtest1` on src, with records keep growing , kill dtle pid of dtle-5(dest dtle-node),  then you will find src keep growing , while dest stop growing ：
![image](https://user-images.githubusercontent.com/17309012/53001357-5b52b900-3465-11e9-87eb-8fac5a122a57.png)
4. wait until job finished, you will find that there are some records missing on dest, and missing records coincidentally be 4938 items
![image](https://user-images.githubusercontent.com/17309012/53001521-c7352180-3465-11e9-8833-7a82b9cf7b88.png)
5. compare src & dest `select id from sbtest1 where id between 99998 and 104940;`
![image](https://user-images.githubusercontent.com/17309012/53002130-e8e2d880-3466-11e9-9c13-17fe338ee00f.png)

**Describe the results you received:**

records on dest are missing between 100000 and 104938

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master 7800c6fba69417f742b18c34c049dd673e62108e)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
1. Always happen
2. When **src** dtle-node was killed while records keep growing，Failover worked with **no** records missing.
3. When dest dtle-node was killed **without** records keep growing，Failover worked with **no** records missing.

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
Deprecating dtle 2.x.

Consistency in 3.x has been imporved.
