### ISSUE TITLE
With failover off,when working dtle(src-dtle or 'src&dest-dtle') dead,job status keep 'running'

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#401]
**Description**

With **failover off**, when working dtle dead(The working dtle maybe the src-dtle or the one src & dest shared) , job stopped but status keep 'running'.

dtle cluster info:
Scenario 1:

| dtle-node |  role | cluster role | job role |
| ------------- | ------------- | ------------- |------------- |
| dtle-4 | manager & agent | member | dest dtle-node  |
| dtle-5 | manager & agent | member | src dtle-node  |
| dtle-6 | manager & agent | leader | -- |

Scenario 2:

| dtle-node |  role | cluster role | job role |
| ------------- | ------------- | ------------- |------------- |
| dtle-4 | manager & agent | member | --  |
| dtle-5 | manager & agent | member | src&dest dtle-node  |
| dtle-6 | manager & agent | leader | -- |

**Steps to reproduce the issue:**
1. prepare table `action_db.sbtest1` with 100000 records by sysbench on src 
2. post a schema level job 'test' with `"Failover":false`
3. when job finished，run sysbench `insert.lua` insert another 100000 recodes on table `action_db.sbtest1` on src, with records keep growing , kill dtle pid of **dtle-5** ,  then you will find src keep growing , while dest stop growing
4. check job status for a while, job stopped but job status keep 'running'

**Describe the results you received:**

check job status for a while, job stopped but job status keep 'running'

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master 7800c6fba69417f742b18c34c049dd673e62108e)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

1. Always happened
2. job status turned 'dead' when dest-dtle dead (dtle-5) ,and that response is correct :

Scenario 3:

| dtle-node |  role | cluster role | job role |
| ------------- | ------------- | ------------- |------------- |
| dtle-4 | manager & agent | member | src dtle-node  |
| dtle-5 | manager & agent | member | dest dtle-node |
| dtle-6 | manager & agent | leader | -- |

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
deprecating dtle 2.x
