### ISSUE TITLE
'GroupMaxSize' or 'GroupTimeout' may not worked when GroupMaxSize is big enough

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#411]
**Description**

'GroupMaxSize' or 'GroupTimeout' may not worked when GroupMaxSize is big enough

`'GroupMaxSize': '1000000'`
`'GroupTimeout': '100'`

**Steps to reproduce the issue:**
1.get GTID on src_mysql
2.prepare data on src_mysql (sysbench 5000 rows)
3.create job use the gtid  in setp 1

**Describe the results you received:**

Data would not copy to dest,even if job is still running
![image](https://user-images.githubusercontent.com/17309012/53882586-aff35800-4051-11e9-8e59-1f45419b055a.png)

**Describe the results you expected:**

No matter what config of `GroupMaxSize` or `GroupTimeout` ,as long as job running, data will copy to dest_mysql without error

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master 6c55f5f8d200302040b50a047ae3de620631cf84)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
When prepare 1000 rows in _step2_, all the data would be copied to dest

**Additional details (log, config, job config etc):**
1. job.conf:
```json
{
    "Name":"test1",
    "Failover":false,
    "Orders":[],
    "Type":"synchronous",
    "Tasks":[
        {
            "Type":"Src",
            "NodeId":"a74bae16-fabe-227c-b8a2-292b19fba804",
            "Config":{
                "Gtid":"8868d98f-af5e-11e8-9aa9-0242ac110002:1-7",
                "SkipCreateDbTable":false,
                "ExpandSyntaxSupport":false,
                "DropTableIfExists":false,
                "ReplChanBufferSize":"600",
                "ChunkSize":"2000",
                "GroupMaxSize":"1000000",
                "GroupTimeout":"100",
                "ApproveHeterogeneous":true,
                "ReplicateDoDb":[
                    {
                        "TableSchema":"db50w",
                        "Tables":[]
                    }
                ],
                "ConnectionConfig":{
                    "Host":"172.100.9.1",
                    "Port":"3306",
                    "User":"test1",
                    "Password":"test1"
                }
            }
        },
        {
            "Type":"Dest",
            "NodeId":"a74bae16-fabe-227c-b8a2-292b19fba804",
            "Config":{
                "SkipCreateDbTable":false,
                "DropTableIfExists":false,
                "ExpandSyntaxSupport":false,
                "ReplChanBufferSize":"600",
                "ChunkSize":"2000",
                "GroupMaxSize":"1000000",
                "GroupTimeout":"100",
                "ApproveHeterogeneous":true,
                "ConnectionConfig":{
                    "Host":"172.100.9.2",
                    "Port":"3306",
                    "User":"test2",
                    "Password":"test2"
                }
            }
        }
    ]
}
```
2.dtle.log
[dtle_log.txt](https://github.com/actiontech/dtle/files/2936325/dtle_log.txt)

**Comment by ffffwh** [comment]
1. dtle.src send an EntryGroup with nEntries = 1400 (limited by GroupMaxSize and GroupTimeout)
2. dtle.dst found nEntries > vacancy (ReplChanBufferSize * 2) and reject the packet
3. dtle.src retries, resulted in dead loop

**Comment by Dinosauria** [comment]
Verified in `Dtle 9.9.9.9 (git: master 3290eba4e901d4492719e7bb57b1df647df418bc)`
Data copied to dest Even with 1705761 rows
