### ISSUE TITLE
Painc when prepare table by  'sysbench prepare'

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#423]
**Description**

Painc when prepare table by 'sysbench prepare'

**Steps to reproduce the issue:**
1. `CREATE DATABASE action_db;`
2. POST a job test for empty schema `action_db`
3. Prepare data by using sysbench
`/data/Action-dtle-testing# /opt/sysbench0.5/bin/sysbench --test=/opt/sysbench0.5/db/oltp.lua --oltp-table-size=10 --oltp-tables-count=1  --num-threads=1  --mysql-db=action_db  --report-interval=20  --mysql-host=172.100.9.1  --mysql-user=test --mysql-password=test --mysql-port=3306 prepare`

**Describe the results you received:**

Panic happened on dtle

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master f8a972770e71438a09a6a472d3f9453c476d7de2)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Always

**Additional details (log, config, job config etc):**

1. job config:   
```
{
    "Name":"test",
    "Failover":false,
    "Orders":[],
    "Type":"synchronous",
    "Tasks":[
        {
            "Type":"Src",
            "NodeId":"ce5312ba-61ee-77e4-22cc-fbc41b060338",
            "Config":{
                "Gtid":"",
                "DropTableIfExists":false,
                "SkipCreateDbTable":false,
                "ApproveHeterogeneous":true,
                "ReplChanBufferSize":"600",
                "ChunkSize":"2000",
                "ExpandSyntaxSupport":false,
                "MsgBytesLimit":"20480",
                "MsgsLimit":"65536",
                "BytesLimit":"67108864",
                "GroupMaxSize":"1",
                "GroupTimeout":"100",
                "SqlFilter":[],
                "ReplicateDoDb":[],
                "ConnectionConfig":{
                    "Host":"172.100.9.1",
                    "Port":"3306",
                    "User":"test1",
                    "Password":"test1"
                }
            }
        },
        {
            "Type":"Dest",
            "NodeId":"ce5312ba-61ee-77e4-22cc-fbc41b060338",
            "Config":{
                "ParallelWorkers":"1",
                "ConnectionConfig":{
                    "Host":"172.100.9.2",
                    "Port":"3306",
                    "User":"test2",
                    "Password":"test2"
                }
            }
        }
    ]
}
```

2. default log path: /var/log/dtle.log
[dtle_log.txt](https://github.com/actiontech/dtle/files/3011244/dtle_log.txt)

**Comment by ffffwh** [comment]
5b76c851: return err when `GetTableColumnsSqle()` failed, thus resulting job dead.

**Comment by Dinosauria** [comment]
Verified in `Dtle 9.9.9.9 (git: master 3db3e66676698648183df520a653ba9a3a39d96c)`
