### ISSUE TITLE
Support breakpoints

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#425]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
全量时，有一个 非一致性 dumper的参数，在代码中有，在配置中没有体现。
非一致性dump时，最好能断点续传
v3 表，看样要加一个类型了
type = full ,incr
v3表加一个列，记录dump range 的范围
**Describe alternatives you've considered**

无法断点续传
    1. dumper异常
    2. BinlogStream异常
    3. Dest写入异常

**Comment by ffffwh** [comment]
Same as #365
