### ISSUE TITLE
mysql.extractor can't connect nats server

### ISSUE THREAD

**Issue by kevinbin** [actiontech/dtle#433]
**Description**
version: dtle 2.19.01 manger和agent在同主机部署

问题1：同步某schema同步过程中，由于binlog被清空导致同步中断，重新设置job，重启job报错mysql.extractor can't connect nats server，
master binlog被人为清理导致
![image](https://user-images.githubusercontent.com/345933/55771294-12f56600-5aba-11e9-81ad-856d393757d9.png)
master的gtid信息
![image](https://user-images.githubusercontent.com/345933/55773564-ba2acb00-5ac3-11e9-828c-89fa8632123b.png)

dtle gtid表内容太多，截取最后部分信息
![image](https://user-images.githubusercontent.com/345933/55773575-cf9ff500-5ac3-11e9-8b89-2c75b7d9dfd1.png)

重设该job，目标端未清理已同步的存量数据
![image](https://user-images.githubusercontent.com/345933/55770352-98771700-5ab6-11e9-95bd-88171f4ffb17.png)

启动job后,当有表被更新时报错
![2701554776255_ pic](https://user-images.githubusercontent.com/345933/55770200-0bcc5900-5ab6-11e9-8dd0-e1a2df3e9904.jpg)

dtle配置信息如下
![image](https://user-images.githubusercontent.com/345933/55770185-fbb47980-5ab5-11e9-8815-6aa843f85797.png)

nats端口信息
![2771554777798_ pic_hd](https://user-images.githubusercontent.com/345933/55770163-ec353080-5ab5-11e9-9924-e6f60ec73390.jpg)

job状态
![image](https://user-images.githubusercontent.com/345933/55770548-4aaede80-5ab7-11e9-9bb7-c0eef2f590b0.png)

报错信息不足以判断问题原因。

**Comment by ffffwh** [comment]
Steps to reproduce the case
1. putjob
2. Ctrl-C dtle after full-copy done
3. start dtle again and see `Can't connect nats server nats://.`

**Comment by ffffwh** [comment]
## Analysis
computePlacements is only called for `diff.place`,
not for `diff.resume`. resumed allocs should use their
saved `NatsAddr`.

It was saved in `udupFSM.applyJobClientUpdate` but later commented out in d83f610. The reason I guess is that there was confliction of `SrcTask.NatsAddr` vs `DestTask.NatsAddr`.

The real problem causing the confliction might be in `Client.allocSync`, TaskUpdates were overwritten by the same JobID, not differentiating the TaskType.

```go
		case update := <-c.workUpdates:
			jUpdates[update.JobID] = update
```
