### ISSUE TITLE
Reduce unnecessary 'select count(*)' at the beginning of the job

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#440]
**Description**

在全量迁移时 create table 阶段会执行 count操作，表创建完了，开始迁移数据时还会count。 所以create  table阶段的 count操作可否省略掉。

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `./dtle version`:**

```
(paste your output here)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
From the code, it is only counted once for each table at
- `CountTableRows` <- `mysqlDump`

Also `SELECT COUNT(*) AS num_triggers FROM INFORMATION_SCHEMA.TRIGGERS` will be executed, which is not counting the original table and takes only a little time.

**Comment by ffffwh** [comment]
A decision should be made whether to get rows count from infoschema

`select table_rows from information_schema.tables where table_schema = '%s' and table_name = '%s'`

PRO

**Comment by ffffwh** [comment]
also see #437
