### ISSUE TITLE
Dtle:when job config error ,job can running

### ISSUE THREAD

**Issue by yaqigithub** [actiontech/dtle#464]
**Description**
when job NodeID config error , job invalid and normal operation

**Steps to reproduce the issue:**
1. create schema and tables in Src 
` create database demo_db;`
`create table `tbl_1`( `id` int(50) NOT NULL, PRIMARY KEY(`id`));`
` create table `tbl_2`( `id` int(50) NOT NULL, PRIMARY KEY(`id`));`
2.create job 
[job.6.20.json.txt](https://github.com/actiontech/dtle/files/3309323/job.6.20.json.txt)

3.show job status
`curl -H "Accept:application/json" -XGET "http://10.186.62.42:9190/v1/job/+jobid" | jq`

**Describe the results you received:**
job running 

**Describe the results you expected:**
job dead
**Output of `./dtle version`:**

```
Dtle 2.19.05.0 (git: 2.19.05.0 6597c279707070cf5217082a229e4b592788ea2d)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**
1、
```

      },
      "ConfigLock": {},
      "Constraints": null,
      "Driver": "MySQL",
      "Leader": false,
      "NodeID": "",
      "NodeName": "",
      "Type": "Src"
    },
    {
      "Config": {
        "Gtid": "8868d98f-af5e-11e8-9aa9-0242ac110002:1-12",
        "ConnectionConfig": {
          "Host": "172.100.9.2",
          "Port": "3306",
          "User": "test2",
          "Password": "test2"
        }
      },
      "ConfigLock": {},
      "Constraints": null,
      "Driver": "MySQL",
      "Leader": true,
      "NodeID": "",
      "NodeName": "",
      "Type": "Dest"
    }


```

**Comment by ffffwh** [comment]
2.x deprecated.
