### ISSUE TITLE
mysql数据同步到kafka, kafka: Shutting down

### ISSUE THREAD

**Issue by taek007** [actiontech/dtle#465]
mysql数据同步到kafka
使用版本:dist/dtle version
Dtle 2.19.05.0 (git: HEAD 6597c27)

安装rpm包 没问题
安装 源码包, 新建kafka任务后报错
"Status": "dead",
"StatusDescription": "DTLE_BUG kafka: unknown table structure",

同时, log日志里

2019/06/23 22:52:25.199420 [DEBUG] [jobid:292cdc1f-7b6c-1787-5d48-dccfe290be1f] mysql.extractor: publish. gtid: , msg_len: 795 
2019/06/23 22:52:25.199602 [DEBUG] [jobid:292cdc1f-7b6c-1787-5d48-dccfe290be1f] kafka: recv a msg 
2019/06/23 22:52:25.199931 [DEBUG] setState 4 
2019/06/23 22:52:25.199942 [DEBUG] setState.SaveState 
2019/06/23 22:52:25.199949 [INFO] [jobid:292cdc1f-7b6c-1787-5d48-dccfe290be1f] kafka: Shutting down 
2019/06/23 22:52:25.200053 [DEBUG] Worker.SaveState: lock: 0xc000162700, 0xc000612be0 
2019/06/23 22:52:25.200065 [DEBUG] Worker.SaveState: after lock: 0xc000162700 
2019/06/23 22:52:25.200070 [DEBUG] Worker.SaveState: after unlock: 0xc000162700 
2019/06/23 22:52:25.200074 [DEBUG] updater 
2019/06/23 22:52:25.200096 [ERR] agent: Task "Dest" for alloc "9d64d961-457b-47bd-e4e1-79932e7a833f" failed: Wait returned exit code 2, and error DTLE_BUG kafka: unknown table structure 
2019/06/23 22:52:25.200108 [INFO] agent: Not restarting task: Dest for alloc: 9d64d961-457b-47bd-e4e1-79932e7a833f

**Comment by ffffwh** [comment]
f0d924db 9007133c 21626bb2 fe307376 6e4838b8
