### ISSUE TITLE
DTLE: When we change dtle configuration，restart the dtle process need delete "data" folder

### ISSUE THREAD

**Issue by yaqigithub** [actiontech/dtle#472]
**Description**
When we change dtle configuration，restart the dtle process need delete "data" folder. If don't delete "data" the change invalid

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `./dtle version`:**

```
(paste your output here)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (log, config, job config etc):**

**Comment by ffffwh** [comment]
re-test on dtle 3.
