### ISSUE TITLE
Dtle：dtle 'panic'  when column with type blob >16M 

### ISSUE THREAD

**Issue by yaqigithub** [actiontech/dtle#485]
## Description
create a table with blob type cloumn ,when data > 16M ,the datle 'panic'

## Steps to reproduce the issue
1. create table in Src mysql
`reset master;`
`create database test1;`
`use test1;`

``CREATE TABLE `sbtest1` (   `id` int(7) NOT NULL,   `title` varchar(40) NOT NULL,   `column_LONGBLOB_1` longblob,   PRIMARY KEY (`id`) ) ENGINE=InnoDB ``
2.  insert data use python
get a file (>16M) in file path

[addblob_data.py.txt](https://github.com/actiontech/dtle/files/3539496/addblob_data.py.txt)
`python  addblob_data.py;`

## Describe the results you received

dtle is 'panic'
## Describe the results you expected
copy success or job dead ,dtle mot 'panic'
## Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master b84e66b99ff35f8406f49f9db4ca6907c4da055f)
```

## Additional information

(e.g. issue happens only occasionally)

## Additional details (log, config, job config etc):
[nohup.txt](https://github.com/actiontech/dtle/files/3539503/nohup.txt)

**Comment by ffffwh** [comment]
Try reducing `ChunkSize` and `ReplChanBufferSize`.

**Comment by yaqigithub** [comment]
cause by issue[ #486](https://github.com/actiontech/dtle/issues/486)
