### ISSUE TITLE
请问支持mysql8.0 增量么

### ISSUE THREAD

**Issue by Rsyncc** [actiontech/dtle#487]

**Comment by ffffwh** [comment]
## 1 Problem `Unknown collation: 'utf8mb4_0900_as_cs'`

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-charset

[job_4.json.txt](https://github.com/actiontech/dtle/files/3589397/job_4.json.txt)

**Comment by ffffwh** [comment]
# 2 Problem
dtle use `select count(*) as rows from %s.%s where (%s)` and such query
`select 1 as row` will cause an error in mysql 8.0.
