### ISSUE TITLE
incremental: prepared statement arg count for update is changing

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#488]
Test case
```sql
drop table if exists a.a488;
create table a.a488 (id int, val int);
insert into a.a488 values (1, null);
insert into a.a488 values (2, 2);

-- do full copy.
-- run following incr

update a.a488 set id=11 where id = 1; -- ok
update a.a488 set id=12 where id = 2; -- cause job dead

-- error: sql: expected 3 arguments, got 4
```

Reason: the first update generate a PS
```sql
update `a`.`a488`
set `id`=?, `val`=?
where ((`id` = ?) and (`val` is NULL))
limit 1
```
which is not suitable for the second update.

The second update requires
```sql
update `a`.`a488`
set `id`=?, `val`=?
where ((`id` = ?) and (`val` = ?))
limit 1
```

The same thing applies to a `delete`.

**Comment by ffffwh** [comment]
## 2
Consider the code of `BuildDMLDeleteQuery`/`BuildDMLUpdateQuery`

Q1 Is the form of u/d query unique when there is PK?
- PK cannot be null.
- Column type does not change.
- Conclusion: the form is unique.

Q2 Do `uniqueKeyComparisons` and `uniqueKeyArgs` appear together?
- For a binary PRI column, `uniqueKeyComparisons` is appended, without `uniqueKeyArgs`.
  - arg is formatted in the comparison
- Q2.2 Is it causing inconsistency?

**Comment by yaqigithub** [comment]
solve in Dtle 9.9.9.9 (git: master 933b599de14f6ac6a776821b9081d8962a48e659)
