### ISSUE TITLE
dtle 无重试机制

### ISSUE THREAD

**Issue by skymoou** [actiontech/dtle#502]

**Comment by skymoou** [comment]
阿里云rds发生高可用切换的时候，会导致dtle直接报错如下：

 "StatusDescription": "mysql.extractor: StreamEvents encountered unexpected error: dial tcp 10.91.107.10:3306: i/o timeout\ngithub.com/actiontech/dtle/vendor/github.com/pingcap/errors.AddStack\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/pingcap/errors/errors.go:174\ngithub.com/actiontech/dtle/vendor/github.com/pingcap/errors.Trace\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/pingcap/errors/juju_adaptor.go:15\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/client.Connect\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/client/conn.go:54\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).registerSlave\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:214\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).prepare\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:335\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).prepareSyncGTID\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:611\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).retrySync\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:578\ngithub.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).onStream\n\t/universe/src/github.com/actiontech/dtle/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:660\nruntime.goexit\n\t/opt/go/src/runtime/asm_amd64.s:1333",





job 配置的地址为rds的域名：
"Host": "rm-xxxxxxx.mysql.rds.aliyuncs.com"


建议dtle能够加上重试机制，以防当数据库超时时候或者发生高可用切换的时候不可用

**Comment by ffffwh** [comment]
In 3.x nomad will restart a dead task (limitedly).
