### ISSUE TITLE
需求：insert/replace时根据表结构指定所要插入数据的列

### ISSUE THREAD

**Issue by ianholyoung** [actiontech/dtle#505]
## 场景
MySQL做数据存储，多数据源汇聚，src表结构与dest表结构不同，dest表结构包含src表结构

## 当前情况
src t1表列 id,name
dest t1表列 id,age,name
dtle执行SQL
**replace into t1 values(1,'a');**
执行报错，无法继续

## 需求建议
insert/replace根据表结构指定所要插入数据的列，即
**replace into t1(id,name) values(1,'a');**

## 可解决
1、本场景报错
2、假如src、dest表结构列元素完全一致，但是顺序不同，可能会导致的数据错乱

请各位老师考虑下此需求，谢谢！

**Comment by ffffwh** [comment]
#965: `ColumnMapTo`
