### ISSUE TITLE
jotb stop ,memory not release

### ISSUE THREAD

**Issue by 790493303** [actiontech/dtle#516]
## Description
when we stop a job,the memory was not release  on time ,it still use.
in dtle，has a 10240 size channel for get data from mysql to src. when we stop the job ,the channel was destroy?

## Steps to reproduce the issue
1. create a mysql ->kafka  job with gitd set

## Describe the results you received
when i stop job ,memory still use by dtle,ont release
![image](https://user-images.githubusercontent.com/21050457/86882731-4ee70300-c123-11ea-903c-6ab0085a713d.png)
![image](https://user-images.githubusercontent.com/21050457/86882799-658d5a00-c123-11ea-86ab-f30a89126442.png)

## Describe the results you expected
memory was release

## Output of `./dtle version`:**
 dtle version for dts
```
(paste your output here)
```

**Comment by ffffwh** [comment]
在go1.12和kernel4.5后, 使用madvise(MADV_FREE)标记释放内存

-   标记的内存计入该进程RSS
-   操作系统可回收
-   如未回收(没有其他进程需要内存), 下次利用该片内存时无需重新分配
-   如已回收, 则下次利用时OS会自动分配

|           | MADV_FREE | MADV_DONTNEED | munmap       |
|--------- |------------------- |----------------------- |------------ |
| 可访问该片虚拟地址 | 可                  | 可                      | 不可(segfault) |
| 访问时    | 未被回收则直接使用  | 重新分配物理内存        | -            |
| 计入RSS   | 是                  | 否                      | 否           |

dtle会获取available并要求available大于一定数值. 计入RSS会导致available比实际少.

应设定环境变量后重测:

> To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1.
