### ISSUE TITLE
cpu  too high

### ISSUE THREAD

**Issue by 790493303** [actiontech/dtle#520]
## Description
when memory use 75%
Start of memory recovery,dtle will have Ultra high CPU utilization.

## Steps to reproduce the issue
1. create  mysql to kafka job whith gtid.
2. table  add  60000 count data.
3. update table. as the some  time ,sysbench 10000000 data  with 6 thread  to the some mysql,

## Describe the results you received
CPU utilization in (120-280)

## Describe the results you expected
cup not so high

**Comment by ffffwh** [comment]
Need flamegraph.
