### ISSUE TITLE
nats Message re-consumption

### ISSUE THREAD

**Issue by 790493303** [actiontech/dtle#521]
## Description
in mysql to kafka job ,if the tx too  big, the data send from source to destination timeout. nats will send agent and agent.as a matter of fact,the message was get by des.
finally ,kafka get the some data all the time.Until kafka node run out of disk space.
in dts ,we change the timeout time  to 180s,it avoided the message re-counsumption, but created a new  question.
so ,we  need a better solution to solve this problem.

**Comment by ffffwh** [comment]
See #514.
