### ISSUE TITLE
同步的时候突然报这个错误

### ISSUE THREAD

**Issue by GodIT** [actiontech/dtle#525]
测试场景：
   1、mysql-src(demo库） -》 mysql-dst（demo库）
   2、demo 有一个张test表，一万记录，执行delete后，就出现如下问题

"StatusDescription": "Too much entriesSize , not enough memory ",

**Comment by GodIT** [comment]
同时测试 插入100万记录，同步的很慢，这个有文档说明如何配置优化吗

**Comment by ffffwh** [comment]
试试新版本
