### ISSUE TITLE
开启 relay log = true 后，会经常出现 parse relay log offset 0 的问题

### ISSUE THREAD

**Issue by zeusYi** [actiontech/dtle#566]
开启 relay log = true 后，会经常出现 parse relay log offset 0 的问题，JOB 会dead ， error 为:
"StatusDescription": "mysql.extractor: StreamEvents encountered unexpected error: file size of relay log /work/dts/data/agent/binlog/0fd70ac6-f3e4-8c8e-4540-cc6738906970/fdaa0680-b9d6-11ea-8200-fa164e6c2d9a.000001/mysql-bin.055298 become smaller\ngithub.com/pingcap/dm/pkg/streamer.relaySubDirUpdated\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/file.go:284\ngithub.com/pingcap/dm/pkg/streamer.(*BinlogReader).parseFile\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/reader.go:353\ngithub.com/pingcap/dm/pkg/streamer.(*BinlogReader).parseFileAsPossible\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/reader.go:238\ngithub.com/pingcap/dm/pkg/streamer.(*BinlogReader).parseDirAsPossible\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/reader.go:206\ngithub.com/pingcap/dm/pkg/streamer.(*BinlogReader).parseRelay\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/reader.go:135\ngithub.com/pingcap/dm/pkg/streamer.(*BinlogReader).StartSync.func1\n\t/Users/yiwenshuo/GoWorkSpace/src/github.com/zeusYi/DTS/vendor/github.com/pingcap/dm/pkg/streamer/reader.go:108\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nparse relay log file mysql-bin.055298 from offset 0 in dir /work/dts/data/agent/binlog/0fd70ac6-f3e4-8c8e-4540-cc6738906970/fdaa0680-b9d6-11ea-8200-fa164e6c2d9a.000001\nparse relay log file mysql-bin.055298 from offset 23490488 in dir /work/dts/data/agent/binlog/0fd70ac6-f3e4-8c8e-4540-cc6738906970/fdaa0680-b9d6-11ea-8200-fa164e6c2d9a.000001",

**Comment by ffffwh** [comment]
follow #567
