### ISSUE TITLE
Extractor sends TX  not continuously when binlog last_committed not the same

### ISSUE THREAD

**Issue by mianhk** [actiontech/dtle#573]
## Description
Cause MySQL5.7 has group replication，the Extractor may send TX not continuously with same last_committed number which may not cause problems,but sometimes may send Skiped TX with skipped last_committednumber.
If we add code of commit https://github.com/actiontech/dtle/commit/c012bca70ca85f3dbed42abc199ee065126d36a4 ,our task will restart but get task error again because the Extractor send TX not  continuously again.
This make **data inconsistent**  unless task restarts immediately.

## Steps to reproduce the issue
1. dtle task starts(with commit c012bca70ca85f3dbed42abc199ee065126d36a4)
2. get error and task stops
```
[ERROR] client.driver_mgr.dtle: found non-continuous tx seq_num. last 393254 this 393256: driver=dtle @module=dtle.applier job=test1  
[ERROR] client.driver_mgr.dtle: onError: driver=dtle @module=dtle.applier err="found non-continuous tx seq_num. last 393254 this 393256" job=test1
```
3. delete code of commit:https://github.com/actiontech/dtle/commit/c012bca70ca85f3dbed42abc199ee065126d36a4  
4. restart task and after while , get  discover a skipped gtid:
`66f3b11f-94e4-11ea-b316-e4434bcc5f74:1-498403910:498403912-498404583` 
5. source MySQL binlog information:
```
#210122  1:46:28 server id 177090053  end_log_pos 337324993     GTID    last_committed=391927   sequence_number=393254  rbr_only=yes
SET @@SESSION.GTID_NEXT= '66f3b11f-94e4-11ea-b316-e4434bcc5f74:498403911'/*!*/;

#210122  1:46:28 server id 177090053  end_log_pos 337325711     GTID    last_committed=391927   sequence_number=393255  rbr_only=yes
SET @@SESSION.GTID_NEXT= '66f3b11f-94e4-11ea-b316-e4434bcc5f74:498403912'/*!*/;

#210122  1:46:28 server id 177090053  end_log_pos 337326431     GTID    last_committed=391927   sequence_number=393256  rbr_only=yes
SET @@SESSION.GTID_NEXT= '66f3b11f-94e4-11ea-b316-e4434bcc5f74:498403913'/*!*/;

...

#210122  1:46:33 server id 177090053  end_log_pos 337805596     GTID    last_committed=393904   sequence_number=393926  rbr_only=yes
SET @@SESSION.GTID_NEXT= '66f3b11f-94e4-11ea-b316-e4434bcc5f74:498404583'/*!*/;


```
6. As we see above, TX of gtid 498403911 has been skipped, if we don't restart task immediately,we will get data inconsistent. And the commit check sequence_number continuous can't solve this problem.

## Describe the results you expected

We may solve this problem by:
1.One possible way is Applier check sequence_number and last_committed number ,this need we set mtsManager a binlog last_committed member as TX excuted.  
2. Check binlogStreamer GetEvent...
## Additional information

(e.g. issue happens only occasionally)

**Comment by ffffwh** [comment]
The restriction of continuous seq_num has been abolished.

https://github.com/actiontech/dtle/issues/572#issuecomment-766656571

**Comment by ffffwh** [comment]
TODO: print warning instead of abort the task on non-continuous seq_num.
