### ISSUE TITLE
源端/目标端填写无法ping通的ip时源端task持续显示为running状态

### ISSUE THREAD

**Issue by s154050727** [actiontech/dtle#606]
## Description
源端/目标端ip如果无法ping通，src allocation显示状态为running，应该是failed

## Steps to reproduce the issue
1. job.json中使用无法ping通的ip
2. 上传任务后调用allocations接口，查看src状态为running

## Describe the results you received
src状态为running

## Describe the results you expected
src状态为failed

## Output of `./dtle version`:**

```
3.21.01.0
```

## Additional information

(e.g. issue happens only occasionally)

## Additional details (log, config, job config etc):

{
	"Job": {
		"Datacenters": [
			"dc1"
		],
		"ID": "test01",
		"TaskGroups": [
			{
				"Name": "src",
				"Tasks": [
					{
						"Affinities": [
							{
								"LTarget": "${node.unique.name}",
								"Operand": "=",
								"RTarget": "test"
							}
						],
						"Config": {
							"BinlogRelay": true,
							"ConnectionConfig": {
								"Host": "10.10.10.10",
								"Password": "password1",
								"Port": 1,
								"User": "user1"
							},
							"Gtid": "",
							"ReplicateDoDb": []
						},
						"Driver": "dtle",
						"Name": "src"
					}
				]
			},
			{
				"Name": "dest",
				"Tasks": [
					{
						"Affinities": [
							{
								"LTarget": "${node.unique.name}",
								"Operand": "=",
								"RTarget": "test"
							}
						],
						"Config": {
							"BinlogRelay": false,
							"ConnectionConfig": {
								"Host": "20.20.20.20",
								"Password": "password2",
								"Port": 2,
								"User": "user2"
							}
						},
						"Driver": "dtle",
						"Name": "dest"
					}
				]
			}
		]
	}
}

**Comment by ffffwh** [comment]
参考修复方案:
- 建立连接时, 使用带Context的接口, 传入会Timeout的Context.

**Comment by LordofAvernus** [comment]
源端目标端需要通过发布/订阅consul数据来同步Nats IP，该步骤在测试目标端task连接MySQL之后，MySQL连接失败会导致目标端无法发布数据，源端一直等待订阅，所以处于一直running态

修复方案：
    目标端订阅consul数据步骤调整到测试连接MySQL之前

**Comment by asiroliu** [comment]
# 复现
# version:
```
3.21.01.1-3.21.01.x-28dee09
```
1. deolpy dtle cluster
2. create job
```
job "test1" {
  datacenters = ["dc1"]

  group "Src" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-1"
      }
    task "src" {
      driver = "dtle"
      config {
        ReplicateDoDb = []
        ConnectionConfig = {
          Host = "172.100.9.111" # 没有部署MySQL
          Port = 3306
          User = "test_src"
          Password = "test_src"
        }
      }
    }
  }
  group "Dest" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-2"
      }
    task "dest" {
      driver = "dtle"
      config {
        ConnectionConfig = {
          Host = "172.100.9.2"
          Port = 3306
          User = "test_dest"
          Password = "test_dest"
        }
      }
    }
  }
}
```
3. check allocation with api
```
shell> curl -s -X GET "http://172.100.9.4:4646/v1/allocations" | jq '.[]|select(.Name=="test1.Src[0]")|.ClientStatus'

# result:
"running"
```

**Comment by asiroliu** [comment]
# 验证
# version:
```
9.9.9.9-master-eb010e4
```
1. deolpy dtle cluster
2. create job
```
job "test1" {
  datacenters = ["dc1"]

  group "Src" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-1"
      }
    task "src" {
      driver = "dtle"
      config {
        ReplicateDoDb = []
        ConnectionConfig = {
          Host = "172.100.9.111" # 没有部署MySQL
          Port = 3306
          User = "test_src"
          Password = "test_src"
        }
      }
    }
  }
  group "Dest" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-2"
      }
    task "dest" {
      driver = "dtle"
      config {
        ConnectionConfig = {
          Host = "172.100.9.2"
          Port = 3306
          User = "test_dest"
          Password = "test_dest"
        }
      }
    }
  }
}
```
3. check allocation with api
```
shell> curl -s -X GET "http://172.100.9.4:4646/v1/allocations" | jq '.[]|select(.Name=="test1.Src[0]")|.ClientStatus'

# 等待一定时间后
# result:
"failed"
```
