### ISSUE TITLE
get dtle dump info

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/dtle#614]
## Is your feature request related to a problem?
to make it convenient to get dump information of dtle

## Describe the solution you'd like
handle signal SIGTTIN to create dump files

**Comment by ColdWaterLW** [comment]
solution:
send signal to dtle by running ```kill -SIGTTIN [dtle_pid]```
dtle will generate dump files into /tmp/dtle_dump_[date-time]

**Comment by asiroliu** [comment]
# 验证
# version:
```
9.9.9.9-master-d961717
```
# step:
1. deploy dtle
2. kill -SIGTTIN [dtle_pid]
![image](https://user-images.githubusercontent.com/4859322/115831426-2925b300-a444-11eb-9440-802819ecb537.png)
