### ISSUE TITLE
support swagger api

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/dtle#626]
## Describe the solution you'd like
import echo-swagger

related to #605

**Comment by ColdWaterLW** [comment]
visit http://ip:8190/swagger/index.html to get overview through swagger ui
![image](https://user-images.githubusercontent.com/36940986/112947600-90b05180-9169-11eb-98dd-1569f98a6c9e.png)

**Comment by ColdWaterLW** [comment]
visit http://ip:8190/swagger/index.html to get overview through swagger ui
![image](https://user-images.githubusercontent.com/36940986/112947600-90b05180-9169-11eb-98dd-1569f98a6c9e.png)

**Comment by asiroliu** [comment]
version:
```
9.9.9.9-master-38b966e
```
目前支持以下api
![image](https://user-images.githubusercontent.com/4859322/116381184-3e854d80-a847-11eb-9b39-1549a992de61.png)
