### ISSUE TITLE
can not get metrics by visiting "ip:port/metrics"

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/dtle#648]
## Description
![image](https://user-images.githubusercontent.com/36940986/115531279-2d789180-a2c7-11eb-9ac6-39e0293b5638.png)

## Steps to reproduce the issue
1. install dtle-3.21.03.0
2. visit ip:port/metrics

## Output of `./dtle version`:**

```
3.21.03.0-3.21.03.x-2df8ad7
```

## Additional information

(e.g. issue happens only occasionally)

**Comment by asiroliu** [comment]
add new autotest case: 
http://10.186.18.21/testing/dtle-testing/-/commit/e9d0578319271b3e9031a15934afd43cf13b1688
