### ISSUE TITLE
NatsMsgMerger resent ordinary msg

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#652]
1. recv a ordinary msg
2. iSeg is set to 1
2. discarded due to no vacancy
3. nmm.Reset() is NOT executed
3. recv the msg again
4. iSeg == 1, go to the logic for big msg

**Comment by ffffwh** [comment]
Plan
- remove timeout - resending
  - TCP should ensure data completeness
- add a new subject '_ping' to detect connection failure

**Comment by ffffwh** [comment]
dst subscribe (watch) nats问题

- 由于没有重传, 需要注意不要丢失第一个msg
- dst先subscribe nats, 再告知src NatsAddr

1. dst: put waitdst
2. src: put wait
3. dst subscribe
4. dst: put nats

**Comment by ffffwh** [comment]
fixed in bdbcfb52

**Comment by asiroliu** [comment]
just need Regression Testing
