### ISSUE TITLE
Write-set based MTS (parallel) incremental replication

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#688]

**Comment by ffffwh** [comment]
# Writeset MTS 效果验证

- 之前: dtle 使用timestamp MTS. 源端MySQL上group_commit的TX可以并行执行.
- 之后: dtle 计算TX的依赖关系, 没有依赖关系的TX可以并行提交.

<details>

## 准备测试数据

源端MySQL执行
```sql
set global binlog_transaction_dependency_tracking = 'COMMIT_ORDER'; -- MySQL默认值
create schema mts;
-- 执行下述 sysbench prepare
show master status; -- 记录Gtid为复制起点
```

```sh
# sysbench 1.0.17
sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=10.186.62.40 --mysql-user=root \
 --mysql-password=password --mysql-port=3307 \
 --threads=1   --table-size=100000 --mysql-db=mts \
 --tables=3 \
 --time=100 --report-interval=1 prepare
```

使用dtle把mts schema全量复制到目标端MySQL. 完成后 *删除job*. 可使用checksum table校验.

在目标MySQL上创建全量数据备份, 使以后可以反复执行增量.
```sql
use mts;
drop table if exists bak1, bak2, bak3;
create table bak1 like sbtest1;
create table bak2 like sbtest2;
create table bak3 like sbtest3;

insert into bak1 select * from sbtest1;
insert into bak2 select * from sbtest2;
insert into bak3 select * from sbtest3;
```

执行sysbench run, 生成增量数据. 注意使用--threads=1, 减少timestamp MTS的有效性.


## 增量job配置
重点
```
# src
DropTableIfExists = false
Gtid = 上面记录的复制起点
# dest
ParallelWorkers = 32
UseMySQLDependency = false
```

## 运行job

运行nomad前注意设置环境变量, 使dtle在日志中打印TPS
```sh
export UDUP_PRINT_TPS=1
nomad agent -config=...
```

运行job
```
nomad job run mts.hcl
```

日志中将打印:
```
    2021-08-06T18:11:24.040+0800 [INFO]  client.driver_mgr.dtle: txLastNSeconds: driver=dtle @module=dtle.applier job=a1-migration n=2488 timestamp=2021-08-06T18:11:24.040+0800
```
其中n=2488为5秒TX数量, TPS=2488/5.

执行完成后, 可验证数据一致性.
```
checksum table sbtest1, sbtest2, sbtest3;
```

开始下一轮测试前, 重置目标端MySQL为job开始前的状态
```sql
truncate table sbtest1;
truncate table sbtest2;
truncate table sbtest3;

insert into sbtest1 select * from bak1;
insert into sbtest2 select * from bak2;
insert into sbtest3 select * from bak3;

drop schema dtle; -- clear gtid_executed
```

注意还要清理consul中的元数据.

</details>

**Comment by ffffwh** [comment]
# 目标端阻塞问题

TODO

**Comment by ffffwh** [comment]
## 暴露目标端阻塞问题的case

形成这样一系列TX, 其中, SEQ=2k的TX之间没有任何依赖, SEQ=2k+1的TX依赖上一个TX

| LC | SEQ | sql          |
|----|-----|--------------|
|  0 |   1 | ...          |
|  1 |   2 | insert (1,0) |
|  2 |   3 | update (1,1) |
|  1 |   4 | insert (2,0) |
|  4 |   5 | update (2,1) |
|  1 |   6 | insert (3,0) |
|  6 |   7 | update (3,1) |

生成上述TX的参考代码

```python
# create table a (id int primary key, val int)
# set autocommit = 1; -- every DML is a TX
N = 10000 # 暂定
for i in range(0, N):
    exec('insert into a values (%s, 0);', i)
    exec('update a set val = 1 where id = %s', i)
```

为了排除源端性能影响, 需要采用“先生成binlog, 再从指定gtidset回放”的方法.

**Comment by ffffwh** [comment]
## 3 unique constraint的影响

table (a PK, b unique)

transactions:
1. insert into (1,1)
2. delete where a = 1
3. insert into (2,1)

如果只考虑PK不考虑其他列的uniqueness, 则2依赖1, 而3不依赖1&2. 3在2之前执行的话, MySQL会报错.

**Comment by asiroliu** [comment]
> ## 暴露目标端阻塞问题的case
> 形成这样一系列TX, 其中, SEQ=2k的TX没有任何依赖, SEQ=2k+1的TX依赖上一个TX
> 
> LC	SEQ	sql
> 0	1	...
> 1	2	insert (1,0)
> 2	3	update (1,1)
> 1	4	insert (2,0)
> 4	5	update (2,1)
> 1	6	insert (3,0)
> 6	7	update (3,1)
> 生成上述TX的参考代码
> 
> ```python
> # create table a (id int primary key, val int)
> # set autocommit = 1; -- every DML is a TX
> N = 10000 # 暂定
> for i in range(0, N):
>     exec('insert into a values (%s, 0);', i)
>     exec('update a set val = 1 where id = %s', i)
> ```
> 
> 为了排除源端(单线程)性能影响, 需要采用“先生成binlog, 再从指定gtidset回放”的方法.
> 
> 应该能观察到, 现有的writeset mts对此类情况性能提升<2倍.

9.9.9.9-master-585b80f

总事务数：20000

源端准备数据用时：105s

UseMySQLDependency = true
耗时: 90s
QPS: 222

UseMySQLDependency = false
耗时: 88s
QPS: 227

# 插入数据的脚本
```python
from datetime import datetime

import pymysql

N = 10000

query_1 = "CREATE TABLE IF NOT EXISTS test.tb1(a INT(11), b INT(11))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
query_2 = "INSERT INTO test.tb1 VALUES (%s, 0);"
query_3 = "UPDATE test.tb1 SET b = 1 WHERE a = %s;"

start_time = datetime.now()
print(f"RUN TIME: {start_time}")

with pymysql.connect(host='10.186.16.109', port=3306, user='test', passwd='test', autocommit=True) as db:
    with db.cursor(pymysql.cursors.DictCursor) as cursor:
        cursor.execute(query_1)

        for i in range(1, N):
            cursor.execute(query_2, (i,))
            cursor.execute(query_3, (i,))

            if i % 100 == 0:
                print(i)

        end_time = datetime.now()
        print(f"END TIME: {end_time}")

        diff = (end_time - start_time).seconds
        print(f'耗时 : {diff}')

```

**Comment by asiroliu** [comment]
version:
9.9.9.9-master-6287a99
job conf: 
```
"ParallelWorkers": 8,
"UseMySQLDependency": false,
```

sql:
```
create table t2 (a INT(11) PRIMARY KEY, b INT(11));

begin;
insert into t2 values (1, 1);
insert into t2 values (2, 2);
insert into t2 values (3, 3);
...
insert into t2 values (10000, 10000);
delete from t2 where a = 1;
delete from t2 where a = 2;
delete from t2 where a = 3;
...
delete from t2 where a = 10000;
insert into t2 values (10001, 1);
commit;
```

目标端打开general.log观测
insert into t2 values (10001, 1); 仍然在所有的delete语句后执行
