### ISSUE TITLE
support pprof web server

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/dtle#690]
## Is your feature request related to a problem?
no

## Describe the solution you'd like
enable urls of go-pprof when api_addr is set. then visit the http://api_addr/debug/pprof to view infomation

![image](https://user-images.githubusercontent.com/36940986/119597859-6818a100-be14-11eb-822d-7593d4976088.png)

**Comment by asiroliu** [comment]
# 验证
## version:
```
9.9.9.9-master-f1ac4b1
```
## reproduce:
1. deploy dtle
2. visit the http://api_addr/debug/pprof/ to view infomation
![image](https://user-images.githubusercontent.com/4859322/120162041-92aa9580-c22a-11eb-90cf-06e54b651752.png)
