### ISSUE TITLE
Monitoring items should use the dtle name as a prefix instead of the host name

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#706]
## Description

Monitoring items should use the dtle name as a prefix instead of the host name

## Steps to reproduce the issue
1. deolpy dtle cluster
 - makesure `publish_metrics` is true
 - set dtle name is `some-custome-dtle-name`
 - set server hostname is `dtle-src-1`
2. create job
3. get monitoring items 'http://{dtle_server_ip}:8190/metrics'

## Describe the results you received
the monitoring item's prefix is server hostname
```
# HELP dtle_dtle_src_1_delay_time dtle_dtle_src_1_delay_time
# TYPE dtle_dtle_src_1_delay_time gauge
dtle_dtle_src_1_delay_time{task_name="109_117_Src"} 0
dtle_dtle_src_1_delay_time{task_name="117_109_Dest"} 0
```

## Describe the results you expected
the monitoring item's prefix should be dtle name
`dtle_some-custome-dtle-name_delay_time{task_name="109_117_Src"}`

## Output of `./dtle version`:**

```
9.9.9.9-master-1db03e8
```

## Additional information

(e.g. issue happens only occasionally)

**Comment by sjjian** [comment]
@asiroliu hi~, what's your expected result?
 
`dtle_dtle_1_delay_time{task_name="109_117_Src"} 0`?

**Comment by asiroliu** [comment]
> @asiroliu hi~, what's your expected result?
> 
> `dtle_dtle_1_delay_time{task_name="109_117_Src"} 0`?

yes

**Comment by sjjian** [comment]
### 方案：
监控项的设计成这样会合理一点：dtle_delay_time{task_name="109_117_Src", dtle_name="some-custome-dtle-name"} ，
1. 但是由于目前无法获取`dtle_name`, 因此暂不实现;
2. 将 `hostname` 信息放到 label 中
3. 参考例子：dtle_delay_time{task_name="109_117_Src", host="dtle-src-1"}
### 原因：
dtle_name 看起来是一个可变的项，应该是一个label，而监控项 delay_time 应该是一个固定的指标，当监控项的key包含可变的值时会导致该监控项无法被唯一确定。例如在配置 grafana 时公式针对每台服务器都需要修改。
