### ISSUE TITLE
support transfer data from oracle to mysql

### ISSUE THREAD

**Issue by re-f** [actiontech/dtle#767]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
- oracle 11g +
- oracle CDC (LogMiner)

### 增量同步
1. Logminer 对接: #813
2. 支持同步DML数据：#812
3. 支持同步DDL数据：#811
4. 支持 索引同步

### 非功能需求
- [x] #835
### 全量同步
- [x] #953

**Comment by sjjian** [comment]
## oracle 到 mysql 的数据同步方案
与mysql 到 mysql 类似，oracle 到 mysql 包括两个阶段，全量数据同步和增量数据同步，其中同步阶段与mysql 的dump类似，增量数据同步采用 logminer 读取数据变更记录
### scn
oracle 内 scn 类似mysql 的 gtid，用来衔接全量同步和增量同步的点位
### 步骤
#### 全量数据同步
1. 确定需要同步的table，并 lock 表防止表结构发生变更，`LOCK TABLE {schema.table} IN ROW SHARE MODE`
2. 获取当前 scn 点位
3. 获取数据库表 structure， 转化为 ddl 事件（也可以是自定义结构或者ddl语句）
4. 释放1中的 lock
5. 通过 scn 点位 dump 需要同步的表中的数据，`select * from {schema.table}  AS OF SCN xxx`（是否分片 limit?），转化为dml事件（也可以是自定义结构或者dml语句）
#### 增量数据同步
1. 通过全量数据同步中确认的 scn 点位，使用 logminer 获取变更语句，生成ddl事件或者dml事件

### logminer 使用
#### 步骤
1. oracle 数据库服务端需要配置启用logminer，启动需要重启oracle
2. 配置完成后 dtle 需要通过oracle sql driver 配置启用 logminer 采集视图，就是需要执行特定的一些 sql 语句
3. 通过select 语句从 logminer 的视图中查询增量数据记录
#### 如何开启 logminer

**Comment by ffffwh** [comment]
oracle log 具体结构是什么样的, 和 mysql binlog 是否有可类比的概念?

- Slave Dump Thread
- Event
  - Gtid/XidEvent
  - Row/QueryEvent

是否有golang库可获取/解析oracle log?

**Comment by sjjian** [comment]
@ffffwh logminer 是 oracle 提供的一种获取 oracle redo log 的日志分析工具，oracle redo log 和 mysql 的不太一样，在当前场景下可以认为 oracle redo log 等价于 mysql binlog。logminer 的使用是由 oracle 服务端提供一个特定的视图，程序可以通过sql driver 执行 sql 从该视图中查询scn 对应的 sql 语句。redo log 的解析工作由 oracle 服务端完成。

**Comment by ffffwh** [comment]
希望mysql/oracle/kafka使用共通的中间数据结构 (现有的 `DumpEntry`、`BinlogEntry`)

**Comment by re-f** [comment]
@sjjian 方案中需要补充, oracle 到 mysql 之间如何做列转换,  列转换的方案中需要考虑后续目标端的数据库可能存在多种的问题, 因此应该使用dtle的数据结构做中转进行转换列,不能直接由oracle列转换成mysql.

**Comment by ffffwh** [comment]
### 潜在性能优化点

据猜测log_miner提供的DML应该是简化的. 只包含字面量, 不包含复杂表达式.

例如
- 用户执行: `insert ... values (1+1, current_date())`
- log_miner: `insert ... values (2, "2020-10-10")`

可使用手写的简易parser, 代替pingcap全功能parser.
