### ISSUE TITLE
after deploying oracle job, the archive_log directory of the oracle instance grows to 100GB+ in 12 hours

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#827]
## Steps to reproduce the issue
1. create oracle jog
2. check archive_log size
```
root@oracle-1:/u01/app/oracle/oradata/archive_log# du --max-depth=1 -h
113G	.
```

## Output of `./dtle version`:**

```
9.9.9.9-oracle_demo-f4bc32e
```

**Comment by sjjian** [comment]
### 背景
DTLE 在同步 Oracle 数据期间 archive log(归档)日志暴涨，和不开启有非常明显的区别，大概周期性的增加几十兆的日志文件
![image](https://user-images.githubusercontent.com/18008452/147055443-60c51b90-6536-49f3-b06c-de121f11f467.png)

### 诊断
1. 几乎可以判定与 logminer 是有相关性的，验证：通过找一些跟归档日志暴涨有关的资料，参考下面这个文档：
https://bbs.csdn.net/topics/392316370  随机挑一个几十兆的文件做 logminer 数据抽取发现记录都跟logminer对应用户有关（10000条内只有50条不是该用户）
![image](https://user-images.githubusercontent.com/18008452/147056030-cf4ef369-b051-40ce-b787-6207153509cb.png)
2. 通过本地测试，发现凡是在执行下面SQL时，就会触发一个几十兆的日志文件，而该SQL会在 logminer 抽取数据的循环内执行，导致可能会频繁的创建几十兆的日志文件。
```sql
BEGIN 
DBMS_LOGMNR_D.build (options => DBMS_LOGMNR_D.STORE_IN_REDO_LOGS);
END;
```
### 修复
该 SQL 仅需要在 DTLE task 启动的时候执行就行

**Comment by asiroliu** [comment]
有效，同样的环境。放一夜志昌盛9.8M的archive log
![image](https://user-images.githubusercontent.com/4859322/147306995-dc1ebf6e-d270-4e1e-9a12-39a0fb86b8b7.png)
