### ISSUE TITLE
use multi-value (bulk) insert / replace

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#829]
对于大量insert, 在目标端应使用形如
`replace into ... values ( ), ( ), ( ), ...`
的语句回放.

要考虑这种回放和prepare statement之间如何整合.

关联问题
- MySQL 一个 RowsEvent 可以表示多行
- dtle中间结构 DataEvent 只表示一行. 需要优化.

**Comment by ffffwh** [comment]
步骤1: 重构DataEvent, 每个DataEvent可对应多行.

引入API版本机制, 避免新老版本混用导致错误.

**Comment by ffffwh** [comment]
## update 拆分问题

对于update前后Where结果不一样的, 需要转化为对应的delete / insert

例如

任务:
- job1: where val % 2 = 0
- job2: where val % 2 = 1

执行: update set val = 3 where val = 0 or val = 1

执行前数据:
- src: (0,0), (1,1)
- dst1: (0,0)
- dst2: (1,1)

执行后:
- src: (0,3), (1,3)

需要执行:
- job1: delete where id = 0
- job2
  - insert values (0,3)
  - update set val = 3 where id = 1

同一个RowEvent (update) 需要被转化为不同的DML. 故update需要保持一个DataEvent对应一行修改.

**Comment by ffffwh** [comment]
- DataEvent.Rows将储存多个insert/delete行。
- 注意大事务拆分原本是基于DataEvent的，现在要注意DataEvent.Rows。

**Comment by ffffwh** [comment]
只有源端bulk insert时，即`insert values (),(),...,()`, dtle才会bulk insert.
源端多次单行insert时，dtle也只进行单行insert，不会合并。

对于bulk insert
- row数目>=8的，每批执行8个
- row数目∈[4,8)的，每批执行4个
- 剩余的，单个执行

job dest 参数
```
BulkInsert1 = 4
BulkInsert2 = 8
```

**Comment by asiroliu** [comment]
源端数据：
```shell
$ sysbench /usr/share/sysbench/oltp_common.lua --mysql-host=xxx --mysql-port=3306 --mysql-user=test --mysql-password=test --mysql-db=test --create_secondary=off --table-size=50000 --tables=8 prepare
```

job json:
```json
{
  "job_id": "mm-d-i-9999",
  "src_task": {
    "connection_config": {
      "database_type": "MySQL",
      "host": "10.186.16.109",
      "port": 3306,
      "user": "test_src",
      "password": "test_src"
    },
    "node_id": "a706ac7a-e6e3-22b7-588b-6b51f435d873",
    "mysql_src_task_config": {
      "gtid": "00003306-0000-0000-0000-000000003306:1-16,5779d606-0983-11ed-b011-b083fecd2cf3:1-4"
    },
    "drop_table_if_exists": true,
    "binlog_relay": false,
    "repl_chan_buffer_size": 120,
    "group_max_size": 1,
    "group_timeout": 100,
    "chunk_size": 2000,
    "task_name": "src",
    "skip_create_db_table": false,
    "replicate_do_db": [
      {
        "table_schema": "test"
      }
    ]
  },
  "is_password_encrypted": false,
  "dest_task": {
    "connection_config": {
      "database_type": "MySQL",
      "host": "10.186.16.117",
      "port": 3306,
      "user": "test_dest",
      "password": "test_dest"
    },
    "node_id": "d89f7993-6234-6606-3ee7-32adadae6a06",
    "mysql_dest_task_config": {
      "use_my_sql_dependency": false,
      "dependency_history_size": 2500,
      "parallel_workers": 8,
      "bulk_insert1": 1,
      "bulk_insert2": 1
    },
    "task_name": "dest"
  },
  "task_step_name": "job_stage_full",
  "failover": true,
  "retry": 2
}
```


![origin_img_v2_c9a4cfa8-bc08-4a55-96c0-c82bfc93e98g](https://user-images.githubusercontent.com/4859322/180380264-06b48db5-b7bc-43e4-87cf-51af3086f477.jpg)

**Comment by ffffwh** [comment]
## 3 MySQL Binlog 中, 一条bulk insert会被分割问题

对于单条 `insert into t values (),(),...,();`, 当每行大小较大时, 一次插入的多行(例如128行), 可能会被分割成若干RowsEvent, 每个Event仅有几行.

9060a568: 在源端, 对可以合并的Insert RowsEvent进行合并.
