### ISSUE TITLE
dtle occupies high memory when extractor reads Oracle SQL 

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dtle#836]
从oracle 读取数据后dtle占用对内存比数据多很多，但是不确定比例，不确定原因
排查进度：
    从火焰图观察到，内存占用最高点为row.next方法。1G的DML可占用超过15G内存。
    
![image](https://user-images.githubusercontent.com/24822803/146756980-c22886f3-8391-4f9d-806f-a7f38e667a18.png)

![image](https://user-images.githubusercontent.com/24822803/146756891-f8b2fa40-9104-46be-a1cf-af063619aa16.png)

排查方向：
   修改oracle driver，使用godor代替当前的driver，是否缓解内存压力

**Comment by LordofAvernus** [comment]
1.更新oracle driver 后 ，有效优化了在读取Oracle数据的时候内存膨胀问题。
同样压测场景下，内存图
![image](https://user-images.githubusercontent.com/24822803/147204938-50ab2ae1-8984-4e6a-ae90-4ac225d2927a.png)

**Comment by re-f** [comment]
> 2.由于新驱动无法关闭连接，导致api接口校验oracle密码使用一次正确密码后，使用错误密码也能通过验证

针对这一点的影响，目前的解决方案是？

**Comment by LordofAvernus** [comment]
背景：
    由于之前的结论是 旧的oracle driver（github.com/godror/godror）在dtle的同步过程中对内存有较大影响, 新的oracle driver（https://github.com/sijms/go-ora）没有问题。
打算给新driver提个issue，提供issue过程中发现，无法用简单的demo场景复现内存膨胀的问题。于是想在dtle环境下模拟出结果。

模拟过程：   
    使用master分支最新的代码(791676a535a52ee9b4b65a860c22ac01c7c15ad8)，并将代码中的Driver改成旧的driver来做内存压力测试
    oracle使用swingbeanch工具进行10分钟数据插入，总共1G数据，涉及11张表。（ 默认的SCN间隔为10W），任务的初始SCN为946830

模拟结果：
      源端30分钟抽取结束,抽取结束后数据已经同步发送到了目标端

      目标端2个小时回放结束

     从高峰期内存pprof图显示，内存压力已经不在driver读取SQL地方，     内存问题似乎已经消失了
   heap_insue_oldDriver.svg

验证：
    为了确认不是压测过程不一致导致的结果偏差。决定使用没做过任何优化的代码来验证一波。

验证一：

    找到最初没有任何优化的代码位置（ 4d9c24caa8e9c9b78679b43beccab86a7997e055），SCN号也从946830开始，创建一个同步任务。内存瓶颈在driver解析行数据函数 heap_inoldCode.svg，并且出现了OOM

Dec 29 03:04:02 localhost kernel: Out of memory: Kill process 11650 (dtle) score 741 or sacrifice child
Dec 29 03:04:02 localhost kernel: Killed process 11650 (dtle) total-vm:13182196kB, anon-rss:12034816kB, file-rss:0kB, shmem-rss:0kBy
验证二：

    找到做了代码优化变更的位置（59a240d1f4a1ac28aee8e033543edd3eeaf0d583），本次commit修改了两个影响点，
    1.修改了源端抽取数据的SCN间隔值，从10W改成了1000

    2.records每读取到一行就通过chan传输到解析方法，解析结束后传输到回放端

在本次代码的基础上将第一个改动暂时回退，SCN号也从946830开始，创建一个同步任务，发现内存压力并不在driver的解析行数据函数

heap_inoldCode2.svg

验证三：

    找到最初没有任何优化的代码位置（ 4d9c24caa8e9c9b78679b43beccab86a7997e055），在此基础上替换driver，内存瓶颈也出现了driver读取SQL的地方，并且也有了OOM的报错

Dec 29 05:16:41 localhost kernel: Out of memory: Kill process 23384 (dtle) score 724 or sacrifice child
Dec 29 05:16:41 localhost kernel: Killed process 23384 (dtle) total-vm:13656000kB, anon-rss:11766344kB, file-rss:0kB, shmem-rss:0kB
heap_inuseOldCodeNewdriver.svg

验证结果如表格：


旧的oracle驱动	新的oracle驱动
代码修改前	内存膨胀，OOM	内存膨胀，OOM
代码修改后	无OOM	无OOM


结论：

     1.用chan同步records,实时消化读取出来的record记录已经解决了内存的压力问题

     2.替换driver驱动解决内存问题是个错误结论，做出错误判断原因是验证过程中，没有控制唯一变量（文章标红），以为减少SCN间隔才导致内存没有压力。

     3. 使用老的驱动不会有连接无法关闭的问题
