### ISSUE TITLE
Pausing the task leads to panic

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dtle#854]
## Description

暂停任务出现panic
GetLogMinerRecord  往关闭的chan records中写入数据，导致panic

## Steps to reproduce the issue
1. Start and stop the same task continuously

## Describe the results you received
 
dtle panic

## Output of `./dtle version`:**
master-9.9.9.9-545beaf4

**Comment by LordofAvernus** [comment]
### 删除job出现panic
**日志：**
client.driver_mgr.dtle: Get log miner record form: driver=dtle EndScn=1.0636129e+07 StartScn=1.0584512e+07 job=asd-sync @module=dtle.ExtractorOracle timestamp=2022-01-05T08:20:14.595Z
![image](https://user-images.githubusercontent.com/24822803/148184572-750ae740-08ea-436a-b9de-7add548324bd.png)

**panic信息：**
Exception has occurred: panic
"send on closed channel"
Stack:
4 0x000000000215c3ee in github.com/actiontech/dtle/drivers/mysql/mysql/oracle/extractor.(*LogMinerStream).GetLogMinerRecord
at /root/workspace/dtle/drivers/mysql/mysql/oracle/extractor/log_miner.go:322
5 0x000000000215f0bb in github.com/actiontech/dtle/drivers/mysql/mysql/oracle/extractor.(*ExtractorOracle).LoopLogminerRecord
at /root/workspace/dtle/drivers/mysql/mysql/oracle/extractor/log_miner.go:805
6 0x000000000215ddf6 in github.com/actiontech/dtle/drivers/mysql/mysql/oracle/extractor.(*ExtractorOracle).DataStreamEvents
at /root/workspace/dtle/drivers/mysql/mysql/oracle/extractor/log_miner.go:555
7 0x0000000002159406 in github.com/actiontech/dtle/drivers/mysql/mysql/oracle/extractor.(*ExtractorOracle).StreamEvents
at /root/workspace/dtle/drivers/mysql/mysql/oracle/extractor/extractor_oracle.go:777
8 0x00000000021592a6 in github.com/actiontech/dtle/drivers/mysql/mysql/oracle/extractor.(*ExtractorOracle).initiateStreaming.func1
at /root/workspace/dtle/drivers/mysql/mysql/oracle/extractor/extractor_oracle.go:649

**Comment by LordofAvernus** [comment]
源端读取oracle redolog方法 LoopLogminerRecord 关闭前，再执行关闭chan的动作

**Comment by LordofAvernus** [comment]
https://github.com/actiontech/dtle/commit/d035a9ef1b90ac774555a85a9546da21bb6a181d

**Comment by asiroliu** [comment]
verify version:
```
4.22.01.0-4.22.01.x-0b7d54d
```
