### ISSUE TITLE
remove passing `ReplChanBufferSize` by consul

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#856]
之前目标端队列存放`BinlogEntry`, 目标端队列不能小于源端ReplChanBufferSize. 否则一次收到的`BinlogEntries` (group)可能无法放下队列.

后来目标端队列存放`BinlogEntries`, 目标端队列大小可以和源端对立.

**Comment by asiroliu** [comment]
version：
```
9.9.9.9-master-05c9de5
```

![image](https://user-images.githubusercontent.com/4859322/149728158-655d9c41-2fc5-4a0d-9416-a27fb43ba09d.png)
