### ISSUE TITLE
api /v2/database/columns has an 500 error

### ISSUE THREAD

**Issue by earthaYan** [actiontech/dtle#861]
## Steps to reproduce the issue
1. 点击新建或者修改任务按钮，进入创建或者修改界面
2. 进入界面，填写完第一步的数据库相关信息，点击下一步
3. 点击迁移对象表格中的列配置的所有列，进行列配置，此时获取数据库列信息的接口 /v2/database/columns 报了500错误，获取列信息失败

## Describe the results you received
{"message":"find db columns failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-test;select COLUMN_NAME from information_schema.columns where table_name='tb1'' at line 1"}
<img width="526" alt="1641806541(1)" src="https://user-images.githubusercontent.com/25888900/148742928-003c63ca-1bd4-447f-8487-022af7bfc411.png">

## Describe the results you expected
接口能够正常获取到数据库的列信息
## Output of `./dtle version`:**

```
9.9.9.9-master-fca543b
```

**Comment by asiroliu** [comment]
验证
version:
```
9.9.9.9-master-05c9de5
```
![image](https://user-images.githubusercontent.com/4859322/149727886-c8c3cedc-5caa-45da-ad33-4a00d564fd87.png)
