### ISSUE TITLE
BinlogRelay / relay vs job deletion 

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#869]
目标: 删除job时删除relay文件.

问题: 无法通过nomad API `StopTask / DestroyTask`来区别彻底删除job还是task转移等情况.

**Comment by LordofAvernus** [comment]
当使用DTLE API删除的时候才视为真正的删除，DTLE API删除会直接清理掉consul上的job数据(dtle/job_name)

extractor 调用了shutdown方法的时候，通过获取consul的job数据，

来确认job数据在consul是否已经被删除，如果已经不存在数据，则直接清空文件夹 nomad_data_dir/binlog/job_name/*
完全清理方案

     可能会由于任务调度，导致部分节点残留binlog relay数据
在extractor shutdown的时候，对比consul上的所有job数据，如果consul上不存在的job名，在nomad_data_dir/binlog下仍然存在文件的话，则清理掉对应文件夹的数据
这样的话能达到正常删除直接清理数据，异常终止延迟清理数据

**Comment by LordofAvernus** [comment]
1.新旧重名job问题。
2.未使用DTLE API维护的job存在风险
