### ISSUE TITLE
Oracle Synchronization case-insensitive Problem

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dtle#893]
## Steps to reproduce the issue
1. create Oracle-MySQL job 
2.source Oracle Execute SQL ：CREATE TABLE "test"."test"(ID INT);

## Describe the results you received
   CREATE TABLE TEST.TEST(ID INT);

## Describe the results you expected
   CREATE TABLE `test`.`test` (`ID` int)
## Output of `./dtle version`:**
9.9.9.9-master-fba74840

**Comment by ffffwh** [comment]
Refer to #849

**Comment by LordofAvernus** [comment]
Oracle同步到MySQL生成DDL过程，使用tidb 解析器的 DefaultRestoreFlags来做解析flag，该flag为 RestoreStringSingleQuotes ，RestoreKeyWordUppercase， RestoreNameBackQuotes三个的并集，由于RestoreKeyWordUppercase的存在，解析时会将所有的关键字都改为大写（包括字段名表名），无法与Oracle字段名保持一致
    
    自定义一个flag 替换默认的flag，新的flag为RestoreStringSingleQuotes ｜ format.RestoreStringWithoutDefaultCharset｜RestoreNameBackQuotes 的并集，解析后符合预期
Oracle DDL ：CREATE TABLE "TEST".number_wildcard_columns(ID INT, C_NUMBER NUMBER(*));
MySQL DDL：CREATE TABLE `TEST`.`NUMBER_WILDCARD_COLUMNS` (`ID` int,`C_NUMBER` double) DEFAULT CHARACTER SET = utf8mb4

**Comment by ffffwh** [comment]
格式调整:

Oracle同步到MySQL生成DDL过程，使用tidb 解析器的 `DefaultRestoreFlags` 来做restore，该flag为 RestoreStringSingleQuotes ，RestoreKeyWordUppercase， RestoreNameBackQuotes三个的并集，由于RestoreKeyWordUppercase的存在，解析时会将所有的关键字都改为大写（包括字段名表名），无法与Oracle字段名保持一致
    
自定义一个flag 替换默认的flag，新的flag为 `RestoreStringSingleQuotes ｜ format.RestoreStringWithoutDefaultCharset｜RestoreNameBackQuotes` 的并集，解析后符合预期

```sql
-- Oracle DDL:
CREATE TABLE "TEST".number_wildcard_columns(ID INT, C_NUMBER NUMBER(*));
-- MySQL DDL:
CREATE TABLE `TEST`.`NUMBER_WILDCARD_COLUMNS` (`ID` int,`C_NUMBER` double) DEFAULT CHARACTER SET = utf8mb4
```
