### ISSUE TITLE
DTLE intermediate structure reconstruction

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dtle#912]
## 背景
       DTLE逐步支持多类型数据库同步，DTLE当前中间态数据结构以MySQL为标准设计，且部分参数为MySQL专有名词。
       为了兼容多类型数据库，避免在代码中看到意义不明的字段。准备调整DTLE中间态数据结构达到通用标准。

###    1.BinlogCoordinateTx
    该字段主要为了记录同步到的点位。 
    将中间态类型修改为Coordinate Interface{} （https://github.com/andyleap/gencode）
    实现方法 ：GetCoordinates()string 获取最后同步点位
    
###    2.BinlogCoordinatesX
    全量同步的最终点位
    将中间态类型修改为DumpCoordinates  []Interface{}
    实现方法 ：GetCoordinates()string 获取当前点位
    
###    3.DDL类型（由于目前目标端场景以MySQL为主，DDL依然使用MySQL SQL格式传输）
    全量同步中存在设置字符集和字符排序的语句
    DDL 同步源端都转为MySQL 支持的SQL语句，目标端根据回放数据库转换执行
    
###    4.DataEvent中logpos 修改为pos
    logpos 当前只在同步到Kafka后展示的一个位置标识。
    源端Oracle传SCN值
    源端MySQL传Logpos

**Comment by ffffwh** [comment]
gencode type.schema 参考
```
struct MySQLCoord {
}

struct OracleCoord {
}

struct BinlogEntry {
    Coordinates union{
        *MySQLCoord
        *OracleCoord
    }
    ...
```

DDL另一种方案:
- 保留原始格式, 增加源端类型标记. 在目标端根据情况决定是否要转换.
