### ISSUE TITLE
add a metric for qps

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#998]

**Comment by LordofAvernus** [comment]
# the source and destination sides have increased the query count

```
ExtractedQueryCount
AppliedQueryCount  
```

**Comment by asiroliu** [comment]
version:
9.9.9.9-master-56b0519

<img width="907" alt="image" src="https://user-images.githubusercontent.com/4859322/182755661-f5a6b5a9-1523-45fa-9e66-fcffaeab326a.png">
